name: VeloxPay
description: "VeloxPay - Smart and Secure Transactions"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  launcher_name: ^1.0.2
  lucide_icons: ^0.257.0
  firebase_dart: ^1.0.9
  go_router: ^14.8.1
  smooth_page_indicator: ^1.2.1
  provider: ^6.1.4
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/finance.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/finance.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/finance.png
  android: true
  ios: true
  fullscreen: true

flutter_launcher_name:
  name: "VeloxPay"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/
